apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  spec:
    hostNetwork: true
    containers:
      - name: kube-apiserver
        image: gcr.io/google_containers/kube-apiserver:9680e782e08a1a1c94c656190011bd02
        command:
          - /bin/sh
          - -c
          - /usr/local/bin/kube-apiserver --address=0.0.0.0 --etcd-servers=http://127.0.0.1:4001
            --cloud-provider=aws --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
            --secure-port=0 --service-cluster-ip-range=10.0.0.0/16
            --basic-auth-file=/srv/kubernetes/basic_auth.csv --cluster-name={{ K8S_CLUSTER_ID }}
            --token-auth-file=/srv/kubernetes/known_tokens.csv --v=2
            --allow-privileged=False 1>>/var/log/kube-apiserver.log 2>&1
    ports:
      - containerPort: 443
        hostPort: 443
        name: https
      - containerPort: 7080
        hostPort: 7080
        name: http
      - containerPort: 8080
        hostPort: 8080
        name: local
        volumeMounts:
          - mountPath: /srv/kubernetes
            name: srvkube
            readOnly: true
      - mountPath: /var/log/kube-apiserver.log
        name: logfile
        volumes:
          - hostPath:
            path: /srv/kubernetes
        name: srvkube
      - hostPath:
        path: /var/log/kube-apiserver.log
        name: logfile

