apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: kube-controller-manager
      image: gcr.io/google_containers/kube-controller-manager-amd64:v{{ K8S_VERSION }}
      command:
        - /bin/sh
        - -c
        - /usr/local/bin/kube-controller-manager
          --address=0.0.0.0
          --port=10252
          --master={{ K8S_MASTER }}
          --kubeconfig=/srv/kubernetes/kubeconfigs/kube-controller-manager.kubeconfig
          --service-account-private-key-file=/srv/kubernetes/kubernetes-key.pem
          --cloud-provider=aws
          --v=2 --logtostderr=true 1>>/var/log/kube-controller-manager.log 2>&1
      livenessProbe:
        httpGet:
          path: /healthz
          port: 10252
        initialDelaySeconds: 15
        timeoutSeconds: 1
      volumeMounts:
        - mountPath: /srv/kubernetes
          name: srvkube
          readOnly: true
        - mountPath: /var/log/kube-controller-manager.log
          name: logfile
        - mountPath: /etc/ssl
          name: etcssl
          readOnly: true
  volumes:
    - hostPath:
        path: /srv/kubernetes
      name: srvkube
    - hostPath:
        path: /var/log/kube-controller-manager.log
      name: logfile
    - hostPath:
        path: /etc/ssl
      name: etcssl
