apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: kube-controller-manager
      image: gcr.io/google_containers/hyperkube:v1.1.3
      env:
        - name: K8S_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      command:
        - /bin/sh
        - -c
        - /hyperkube controller-manager
          --address={{ K8S_IP }}
          --port=10252
          --master={{ K8S_MASTER }}
          --kubeconfig=/srv/kubernetes/kubeconfigs/kube-controller-manager.kubeconfig
          --service-account-private-key-file=/srv/kubernetes/api-key.pem
          --v=2 --logtostderr=true 1>>/var/log/kube-controller-manager.log 2>&1
      livenessProbe:
        httpGet:
          path: /healthz
          port: 10252
        initialDelaySeconds: 15
        timeoutSeconds: 1
      volumeMounts:
        - mountPath: /srv/kubernetes
          name: srvkube
          readOnly: true
        - mountPath: /var/log/kube-controller-manager.log
          name: logfile
  volumes:
    - hostPath:
        path: /srv/kubernetes
      name: srvkube
    - hostPath:
        path: /var/log/kube-controller-manager.log
      name: logfile
