apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: gcr.io/google_containers/hyperkube:v1.1.3
      command:
        - /bin/sh
        - -c
        - /hyperkube scheduler
          --address=0.0.0.0 --port=10251
          --master=127.0.0.1:8080
          --v=2 --logtostderr=true 1>>/var/log/kube-scheduler.log 2>&1
      livenessProbe:
        httpGet:
          path: /healthz
          port: 10251
        initialDelaySeconds: 15
        timeoutSeconds: 1
      volumeMounts:
        - mountPath: /var/log/kube-scheduler.log
          name: logfile
  volumes:
    - hostPath:
        path: /var/log/kube-scheduler.log
      name: logfile
