apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
spec:
  hostNetwork: true
  containers:
    - name: kube-apiserver
      image: gcr.io/google_containers/hyperkube:v1.1.3
      command:
        - /bin/sh
        - -c
        - /hyperkube apiserver
          --insecure-bind-address=127.0.0.1 --insecure-port=8080
          --address=0.0.0.0 --secure-port=443
          --cloud-provider=aws
          --cluster-name={{ K8S_CLUSTER_ID }}
          --etcd-servers=http://127.0.0.1:2379
          --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
          --service-cluster-ip-range=10.0.0.0/16
          --token-auth-file=/srv/kubernetes/known_tokens.csv
          --client-ca-file=/srv/kubernetes/ca.pem
          --tls-cert-file=/srv/kubernetes/api.pem --tls-private-key-file=/srv/kubernetes/api-key.pem
          --allow-privileged=False
          --v=2 --logtostderr=true 1>>/var/log/kube-apiserver.log 2>&1
      ports:
        - containerPort: 443
          hostPort: 443
          name: https
        - containerPort: 8080
          hostPort: 8080
          name: local
      volumeMounts:
        - mountPath: /srv/kubernetes
          name: srvkube
          readOnly: true
        - mountPath: /var/log/kube-apiserver.log
          name: logfile
  volumes:
    - hostPath:
        path: /srv/kubernetes
      name: srvkube
    - hostPath:
        path: /var/log/kube-apiserver.log
      name: logfile
